---
title: PhySoc Temp Site Test Site
timezone: Europe/London
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: quangnguyen30795@gmail.com
description: Temporary static PhySoc Website using Jekyll
baseurl: ''
url: ''
twitter_username: 
github_username: ngcaden
markdown: kramdown
theme: minima
gems:
- jekyll-feed
